repo_url: https://github.com/2418071565/2418071565.github.io.git
site_name: Made By Cyb

copyright: "CopyRight &copy CYB"
edit_uri: edit/master/docs

nav:
  - About: 
    - ğŸ‘¨â€ğŸ’»: index.md
    - ğŸ˜‹: hobbies.md
  - æ•°æ®ç»“æ„ä¸ç®—æ³•: 
    - ç®€ä»‹: DS_Algo.md
    - ç®—æ³•: 
      - åŠ¨æ€è§„åˆ’ï¼ˆæœªå®Œå·¥ï¼‰:
        - èƒŒåŒ…é—®é¢˜: Algorithm/DP/Knapsack/Knapsack.md
      - å€å¢: Algorithm/BinaryLifting/BinaryLifting.md
      - æ’åºï¼ˆæœªå®Œå·¥ï¼‰: 
        - ç®€ä»‹: Algorithm/Sort/Sort.md
        - å†’æ³¡æ’åº: Algorithm/Sort/BubbleSort/Bubble.md
    - å­—ç¬¦ä¸²:
      - å­—å…¸æ ‘: String/Trie/Trie.md
      - å­—ç¬¦ä¸²å“ˆå¸Œ: String/StringHash/StringHash.md
      - KMP: String/KMP/KMP.md
      - é©¬æ‹‰è½¦: String/Manacher/Manacher.md
    - æ•°æ®ç»“æ„:
      - å †: 
        - äºŒå‰å †: DS/Heap/BinHp.md
      - å“ˆå¸Œè¡¨: DS/HTable/HTable.md
      - å¹¶æŸ¥é›†: DS/UnionFind/UF.md
      - åˆ†å—: DS/Block/Block.md
      - æ ‘çŠ¶æ•°ç»„: 
        - æ ‘çŠ¶æ•°ç»„: DS/BIT/BIT.md
        - äºŒç»´æ ‘çŠ¶æ•°ç»„: DS/BIT/2_BIT.md
      - å¹³è¡¡æœç´¢æ ‘: 
        - Splay: DS/Splay/Splay.md
        - B æ ‘: DS/BTree/BTree.md
        - AVLï¼ˆå¾…ä¿®æ”¹ï¼‰: DS/AVLTree/AVL.md
      - çº¿æ®µæ ‘: 
        - åŸºç¡€çº¿æ®µæ ‘ï¼ˆå¾…ä¿®æ”¹ï¼‰: DS/SegTr/SegTr.md
        - å‰å¦‚ä¸€çº¿æ®µæ ‘: DS/SegTr/JRYSegTr.md
    - å›¾è®º: 
      - å›¾çš„å­˜å‚¨: Graph/StorageOfGraphs/Storage.md
      - æ‹“æœ´æ’åº: Graph/TopoSort/Topo.md
      - æ ‘ï¼ˆæœªå®Œå·¥ï¼‰: 
        - æ ‘åŸºç¡€: Graph/Tree/Basic/Basic.md
        - æœ€å°ç”Ÿæˆæ ‘: Graph/Tree/MST/MST.md
        - æ ‘é“¾å‰–åˆ†: Graph/Tree/hld/hld.md
      - å¼ºè¿é€šç›¸å…³:
        - å¼ºè¿é€šåˆ†é‡: Graph/scc/scc.md
    - æ•°å­¦:
      - è®¡ç®—å‡ ä½•:
        - äºŒç»´è®¡ç®—å‡ ä½•åŸºç¡€: Math/Geometry/2DGeometry/2D.md
        - å‡¸åŒ…: Math/Geometry/ConvexHull/CH.md
      - æ•°è®º:
        - æ•°è®ºåŸºç¡€: Math/NumberTheory/Fd.md
        - å¿«é€Ÿå¹‚: Math/NumberTheory/Qpow/qpow.md
        - ä¹˜æ³•é€†å…ƒ: Math/NumberTheory/Inv/Inv.md
        - ç­›æ³•: Math/NumberTheory/sieve/sieve.md
      - æ•°å€¼è®¡ç®—:
        - ç‰›é¡¿è¿­ä»£æ³•: Math/Numerical/NtsMethod/Nt.md
        - å¿«é€Ÿå¹³æ–¹æ ¹å€’æ•°ç®—æ³•: Math/Numerical/QSqrt/QSqrt.md
    - é—®é¢˜æ€»ç»“:
      - æ•´æ•°æ‹†åˆ†: UsualQ/IntPartition/IntPartition.md
      - åŒºé—´æœ€å¤§å­æ®µå’Œ: UsualQ/MaxSumOfSub/MaxSumOfSub.md
      - æš‘æœŸé›†è®­: UsualQ/SummerTraining/SumTraining.md
  - æ“ä½œç³»ç»Ÿ:
    - ç®€ä»‹: OSindex.md
    - å·¥å…·:
      - æŒ‡ä»¤ï¼ˆæœªå®Œå·¥ï¼‰: Linux/Tools/Cmd/Cmd.md
      - ç³»ç»Ÿè°ƒç”¨: Linux/Tools/Syscall/Syscall.md
      - GNU å·¥å…·é“¾:
        - gcc: Linux/Tools/GNU/gcc/gcc.md
        - gdb: Linux/Tools/GNU/gdb/gdb.md
        - make: Linux/Tools/GNU/make/make.md
        - flex: Linux/Tools/GNU/flex_yacc/flex.md
    - åŸºç¡€çŸ¥è¯†:
      - æ¦‚å¿µ: Linux/SysConcept/SysConcept.md
      - è¿›ç¨‹:
        - è¿›ç¨‹æ¦‚å¿µ: Linux/ProCon/ProCon.md
        - è¿›ç¨‹çŠ¶æ€: Linux/ProStatus/ProStatus.md
        - è¿›ç¨‹æ§åˆ¶: Linux/ProCtrl/ProCtrl.md
        - è¿›ç¨‹é—´é€šä¿¡: Linux/IPC/IPC.md
        - å®ˆæŠ¤è¿›ç¨‹: Linux/DaePro/DaePro.md
      - ä¿¡å·: Linux/Signal/signal.md
      - çº¿ç¨‹: 
        - çº¿ç¨‹åŸºç¡€: Linux/Thread/Thread.md
        - çº¿ç¨‹äº’æ–¥ä¸åŒæ­¥: Linux/Thread/Sync.md
        - çº¿ç¨‹æ± : Linux/Thread/Tpool.md
      - æ–‡ä»¶ç³»ç»Ÿ:
        - åŸºç¡€ IO: Linux/FileSys/FileIO/FileIO.md
        - ext2 æ–‡ä»¶ç³»ç»Ÿ: Linux/FileSys/FileSys/FileSys.md
        - è™šæ‹Ÿæ–‡ä»¶ç³»ç»Ÿ: Linux/FileSys/VFS/VFS.md
      - I/O:
        - I/O æ¨¡å‹: Linux/IO/IOmodel/model.md
        - å¤šè·¯å¤ç”¨: Linux/IO/Multiplexing/Multiplexing.md
    - å…¶ä»–:
      - æ ¹ç›®å½•: Linux/others/root/root.md
      - ç¯å¢ƒå˜é‡: Linux/others/envir/envir.md
      - åŠ¨æ€åº“å’Œé™æ€åº“: Linux/others/Lib/Lib.md
      - SheBang: Linux/others/sheBang/sheBang.md
  - è®¡ç®—æœºç½‘ç»œ: 
    - ç®€ä»‹: Network/index.md
    - ä¸“ä¸šæœ¯è¯­: Network/pro_term.md
    - åº”ç”¨å±‚:
      - æ¦‚è¿°: Network/Application/index.md
      - HTTP: Network/Application/http.md
      - DHCP: Network/Application/dhcp.md
    - ä¼ è¾“å±‚:
      - æ¦‚è¿°: Network/Transport/index.md
      - UDP: Network/Transport/udp.md
      - TCP: Network/Transport/tcp.md
    - ç½‘ç»œå±‚:
      - æ¦‚è¿°: Network/network/index.md
      - IPv4: Network/network/ip.md
      - ICMP: Network/network/icmp.md
    - é“¾è·¯å±‚:
      - æ¦‚è¿°: Network/link/index.md
      - Ethernet: Network/link/Ethernet.md
    - socket ç¼–ç¨‹:
      - åŸºç¡€: Network/basic/basic.md
      - è‡ªå®šä¹‰åè®®: Network/socket/Custom.md
      - Socket: Network/socket/socket.md
  - C++:
    - ç®€ä»‹: C++/intro.md
    - åŸºç¡€: C++/c++åˆé˜¶æ‚é¡¹.md
    - æ¨¡æ¿åŸºç¡€: C++/æ¨¡æ¿.md
    - ç»§æ‰¿å¤šæ€:
      - ç»§æ‰¿: C++/ç»§æ‰¿å¤šæ€/ç»§æ‰¿.md
      - å¤šæ€: C++/ç»§æ‰¿å¤šæ€/å¤šæ€.md
    - å†…å­˜ç®¡ç†: C++/å†…å­˜ç®¡ç†/new&delete.md
    - å¼‚å¸¸å¤„ç†: C++/å¼‚å¸¸å¤„ç†/å¼‚å¸¸.md
    - å¼ºåˆ¶ç±»å‹è½¬æ¢: C++/typeCast.md
    - IO æµ: C++/IOæµ/IO.md
    - C++11:
      - åˆ—è¡¨åˆå§‹åŒ–: C++/c++11/åˆ—è¡¨åˆå§‹åŒ–.md
      - ç±»çš„æ–°åŠŸèƒ½: C++/c++11/ç±»çš„æ–°åŠŸèƒ½.md
      - ç±»å‹å£°æ˜: C++/c++11/ç±»å‹å£°æ˜.md
      - åŸå§‹å­—ç¬¦ä¸²: C++/c++11/åŸå§‹å­—ç¬¦ä¸².md
      - å³å€¼å¼•ç”¨å’Œç§»åŠ¨è¯­ä¹‰: C++/c++11/å³å€¼å¼•ç”¨å’Œç§»åŠ¨è¯­ä¹‰.md
      - æ™ºèƒ½æŒ‡é’ˆ: C++/c++11/æ™ºèƒ½æŒ‡é’ˆ.md
      - STL çš„æ”¹åŠ¨ï¼ˆæœªå®Œå·¥ï¼‰: C++/c++11/STL.md
      - æ¨¡æ¿ç›¸å…³: C++/c++11/cppmate.md
      - å¤šçº¿ç¨‹ç›¸å…³: C++/c++11/å¤šçº¿ç¨‹.md
    - C++14:
      - æ¨¡æ¿ç›¸å…³: C++/c++14/cppmate.md
      - decltype(auto): C++/c++14/decltype(auto).md
    - C++17:
      - æ¨¡æ¿ç›¸å…³: C++/c++17/cppmate.md
      - æ–‡ä»¶åº“: C++/c++17/filesystem.md
      - if è¯­å¥: C++/c++17/ifstatement.md
      - ç»“æ„åŒ–ç»‘å®š: C++/c++17/StructBinding.md
    - C++20:
      - ä¿¡å·é‡: C++/c++20/semaphore/semaphore.md
      - format: C++/c++20/format/format.md
  - æ•°æ®åº“ç³»ç»Ÿ:
    - Introduction: DB/index.md
    - SQL: 
      - åº“æ“ä½œ: DB/SQL/BaseOp.md
      - è¡¨æ“ä½œ: DB/SQL/Op.md
      - æ•°æ®ç±»å‹: DB/SQL/DataType.md
      - è¡¨çš„çº¦æŸ: DB/SQL/table/constraints.md
      - è¡¨çš„å¢åˆ æŸ¥æ”¹: DB/SQL/table/idsu.md
      - MySQL å†…ç½®å‡½æ•°: DB/SQL/table/buildin_fun.md
      - å¤åˆæŸ¥è¯¢: DB/SQL/Query.md
    - Database Storage: DB/storage/storage.md
    - Memory Management: DB/BufferPool/BufferPool.md
    - Access Methods: 
      - Hash Tables: DB/DS/HTable.md
      - Trees Indexes: DB/DS/Bplus.md
      - Index Concurrency Control: DB/DS/CC.md
    - Operator Execution:
      - Sorting & Aggregations Algorithms: DB/OpExe/sort.md
      - Joins Algorithms: DB/OpExe/join.md
      - Query Processing: DB/OpExe/query.md
      - Parallel Executin: DB/OpExe/pe.md
      - Query Planning & Optimization: DB/OpExe/qo.md
    - Concurrency Control:
      - Concurrency Control Theory: DB/CC/cct.md
      - Two Phase Locking: DB/CC/tpl.md
      - Timestamp Ordering Concurrency Control: DB/CC/TOCC.md
  - Others:
    - Git: 
      - ç®€ä»‹: Others/Git/index.md
    - JSON:
      - ç®€ä»‹: Others/JSON/index.md
    - cmake: 
      - ç®€ä»‹: Others/CMake/HelloWorld.md
    - xmake:
      - ç®€ä»‹: Others/xmake/index.md
      - xmake.lua è¯­æ³•: Others/xmake/config.md
    - æ™ºèƒ½æŒ‡é’ˆæ‚è°ˆ: Others/SPoiner.md
    # - é¢è¯•: 
    #   - è‡ªæˆ‘ä»‹ç» : Others/interview/ps.md
    #   - C++: Others/interview/Cpp.md


theme:
  name: material
  palette: 
    primary: white
  language: zh
  custom_dir: overrides/
  favicon: Web_icon.svg
  features: 
    - content.code.select
    - content.code.copy
    - navigation.instant
    - navigation.tabs
    - navigation.path
    - navigation.instant.progress
    - navigation.footer
    - content.tabs.link
    - search.highlight
  icon:
    admonition:
      code: material/note-alert
    logo: Web_icon
    repo: repo_icon


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
    
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css

extra:
  social: 
    - icon: fontawesome/brands/github
      link: https://github.com/2418071565/2418071565.github.io.git
    - icon: fontawesome/solid/paper-plane
      link: mailto:idlecyb@163.com


